name: expressions
description: A library to parse and evaluate simple expressions.
version: 0.1.4
homepage: https://github.com/appsup-dart
author: Rik Bellens <rik.bellens@appsup.be>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  quiver: ">=0.24.0 <3.0.0"
  petitparser: ">=2.0.0 <4.0.0"


dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.9.0
