name: expressions
description: A library to parse and evaluate simple expressions.
version: 0.1.0
#homepage: https://www.example.com
#author: rbellens <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  quiver: ">=0.24.0 <0.30.0"
  typedparser: ^0.1.1


dev_dependencies:
  test: ^0.12.0
