name: expressions
description: A library to parse and evaluate simple dart and javascript like expressions.
version: 0.1.5
homepage: https://github.com/appsup-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  quiver: ">=0.24.0 <3.0.0"
  petitparser: ">=2.0.0 <4.0.0"


dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.9.0
